### ISSUE TITLE
Wire up sensors

### ISSUE THREAD

**Issue by dbmage** [dbmage/HeatingPi#14]
Without the sensors, the directory containing the data that I need to pull and log, does not exist.
Once a sensor is connected I can poll it

**Comment by dbmage** [comment]
Docs: https://tutorials-raspberrypi.com/raspberry-pi-temperature-sensor-1wire-ds18b20/

**Comment by daveash** [comment]
4 sensors are now connected but only 3 data wires are connected so the Pi should see 3 of them.
There will be 10 in total so far for me & more later for Vicky.

**Comment by dbmage** [comment]
output visible at http://ivinghoe.ddns.net:8080/admin/temps.php
Also manual test doable with button
